apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

components:
- ../components/provider-extension

patches:
- target:
    version: v1alpha1
    group: operator.gardener.cloud
    kind: Extension
    name: example-extension
  patch: |-
    - op: replace
      path: /metadata/name
      value: local
    - op: replace
      path: /spec/resources/0/type
      value: local
    - op: replace
      path: /spec/resources/1/type
      value: local
    - op: replace
      path: /spec/resources/2/type
      value: local
    - op: replace
      path: /spec/resources/3/type
      value: local
    - op: replace
      path: /spec/resources/4/type
      value: local
    - op: replace
      path: /spec/resources/5/type
      value: local
    - op: replace
      path: /spec/resources/6/type
      value: local
    - op: replace
      path: /spec/deployment/extension/helm/ociRepository
      value: https://gcr.eu/foo/bar
