image: local-skaffold/gardener-extension-admission-local:latest
imagePullPolicy: IfNotPresent
priorityClassName: gardener-garden-system-400
replicaCount: 1
resources: {}
healthPort: 8081
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"
webhookConfig:
  serverPort: 10250

# projectedKubeconfig:
#   baseMountPath: /var/run/secrets/gardener.cloud
#   genericKubeconfigSecretName: generic-token-kubeconfig
#   tokenSecretName: access-local-admission

  service:
    topologyAwareRouting:
      enabled: false
